# Generated by Django 2.2 on 2019-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=11)),
                ('name', models.CharField(default=None, max_length=30)),
                ('email', models.EmailField(max_length=32, null=True)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
